### ISSUE TITLE
KlarnaPaymentView is not loading klarna payment screen in android

### ISSUE THREAD

**Issue by aniket283** [klarna/klarna-mobile-sdk#70] opened 2020-11-11 10:31 UTC
I am using KlarnaPaymentView for my android project 
It is not loading klarna payment screen in physical devices
But in emulator it is working fine
Previously it was working in physical devices as well
Klarna library that I am using : 'com.klarna.mobile:sdk:2.0.16'

Code for klarna:
private void initViews() {
        mPaymentView = findViewById(R.id.paymentView);
        mPaymentView.setCategory("pay_over_time");
        mProceed = findViewById(R.id.button_proceed);
        mPaymentView.registerPaymentViewCallback(mCallback);
        mPaymentView.initialize(klarnaSessionResponse.getClientToken(), "https://vendiapp.com");
        mProceed.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mPaymentView.authorize(true, null);
            }
        });
    }

    private KlarnaPaymentViewCallback mCallback = new KlarnaPaymentViewCallback() {
        @Override
        public void onInitialized(@NotNull KlarnaPaymentView klarnaPaymentView) {
            klarnaPaymentView.load(null);
        }

        @Override
        public void onLoaded(@NotNull KlarnaPaymentView klarnaPaymentView) {
            paymentInProcessView.setVisibility(View.GONE);
            mPaymentView.setVisibility(View.VISIBLE);
            mProceed.setVisibility(View.VISIBLE);
            getSupportActionBar().show();
        }

        @Override
        public void onLoadPaymentReview(@NotNull KlarnaPaymentView klarnaPaymentView, boolean b) {
            LogUtils.d("values on authorized",
                    "onLoadPaymentReview");
        }

        @Override
        public void onAuthorized(@NotNull KlarnaPaymentView klarnaPaymentView, boolean approved,
                @Nullable String authToken, @Nullable Boolean finalizedRequired) {
            LogUtils.d("values on authorized",
                    " " + approved + " " + authToken + " " + finalizedRequired);
            if (authToken != null) {
                setupKlarnaBuyViewModel(new KlarnaAuthToken(authToken));
                // authorization is successful, backend may create order
            }
        }

        @Override
        public void onReauthorized(@NotNull KlarnaPaymentView klarnaPaymentView, boolean approved,
                @Nullable String authToken) {
            LogUtils.d("values on authorized",
                    "onReauthorized");
        }

        @Override
        public void onFinalized(@NotNull KlarnaPaymentView klarnaPaymentView, boolean approved,
                @Nullable String authToken) {
            LogUtils.d("values on authorized",
                    "onFinalized");
        }

        @Override
        public void onErrorOccurred(@NotNull KlarnaPaymentView klarnaPaymentView,
                @NotNull KlarnaPaymentsSDKError klarnaPaymentsSDKError) {
            LogUtils.d("values on authorized",
                    "onErrorOccurred " + klarnaPaymentsSDKError.getMessage());
            startPaymentFailureActivity(getString(R.string.payment_failed_with_klarna));
        }
    };

**Comment by NMGuner** [comment] 2020-12-28 12:37
Hi @aniket283, 

Firstly, sorry for the late response. I can inform that we have not faced this issue before and could not reproduce it in such device. If you are still facing this problem please you elaborate a bit more with information about which callbacks are received or the stacktrace. Also, can this be related to a network configuration on the real device? 

We definitely would like to support you, hence looking forward to your feedback.

**Comment by NMGuner** [comment] 2021-01-25 12:47
Hi @aniket283, 

We are closing the issue, but we would like ask you if it still occurs for you and for any other information that can help us resolve it. Feel free to re-open the issue or contact us even if it is closed.

**Closed by NMGuner** 2021-01-25 12:47 UTC
