### ISSUE TITLE
Description (Readme) is misleading

### ISSUE THREAD

**Issue by Sharkcoon** [klarna/klarna-mobile-sdk#212] opened 2023-09-01 12:28 UTC
**Describe the bug**
In your Readme file you state the following:
_Are you looking for Klarna Checkout? Check out the [Klarna Checkout SDK](https://github.com/klarna/kco-mobile-sdk) repo instead._

We have implemented the Checkout SDK (kco) for iOS and Android native Apps but as i found out on August 29th at around 2pm (UTC+2) it stopped working. In the documentation i luckily found further information.
https://docs.klarna.com/mobile-sdk/checkout-sdk/
Thats the migration guide for the kco SDK which is deprecated but still suggested here.

Furthermore there were no deprecation warnings what so ever. This means any App version shipped with the kco SDK does not support Klarna payments anymore

**Expected behavior**
Correct information in Readme files.

**Impact Level**
Developer understanding

**Comment by NMGuner** [comment] 2023-09-04 15:06
Hi @Sharkcoon, I am sorry for any convenience caused by the deprecation. I am actually surprised the CheckoutSDK stopped working for you. Even if we deprecated it the latest version(s) should still work fine, on our side we haven't made any changes that would break apps integrating it. Considering there are still apps which are not migrated, or end-users who haven't updated migrated apps that would cause a huge issue. Thus, to make sure can you provide any error from your integration with us please. If you provide us your merchant information we can also check if any other change has caused this issue.

As for the changes in docs and the deprecation, we are still in progress of updating our docs including the readme here, thus I will make sure there will be no conflicting information here as well.

**Comment by NMGuner** [comment] 2023-09-19 15:04
I will be closing this issue as the outdated information is removed from the readme.

**Closed by NMGuner** 2023-09-19 15:04 UTC
